spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: david01
  jpa:
    show-sql: true
    format-sql: true
    hibernate:
      ddl-auto: update                              # create                                     
      dialect: org.hibernate.dialect.MySQL5Dialect